version: '3'
services:
  web: 
    container_name: web 
    build: . 
    ports: 
      - 127.0.0.1:8000:8000 
    depends_on:
      - mysql_server
    
  mysql_server:
    image: mysql:latest 
    environment:
      - MYSQL_DATABASE=dcw_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin1267!
    
